gzip on;
gzip_types
  application/javascript
  text/css;
map $upstream_http_content_security_policy $content_security_policy {
  '' "default-src 'self';";
}
map $upstream_http_permissions_policy $permissions_policy {
  '' "camera=(), microphone=(), geolocation=()";
}
map $upstream_http_referrer_policy $referrer_policy {
  '' "strict-origin-when-cross-origin";
}
map $upstream_http_strict_transport_security $strict_transport_security {
  '' "max-age=31536000; includeSubDomains; preload";
}
map $upstream_http_x_content_type_options $x_content_type_options {
  '' "nosniff";
}
map $upstream_http_x_frame_options $x_frame_options {
  '' "DENY";
}
server {
  listen 80;
  root /var/www/html/public;
  index index.php;
  add_header Content-Security-Policy $content_security_policy;
  add_header Permissions-Policy $permissions_policy;
  add_header Referrer-Policy $referrer_policy;
  add_header Strict-Transport-Security $strict_transport_security;
  add_header X-Content-Type-Options $x_content_type_options;
  add_header X-Frame-Options $x_frame_options;
  location / {
    try_files $uri /index.php?$query_string;
  }
  location ~ \.php$ {
    fastcgi_pass app:9000;
    include fastcgi_params;
    fastcgi_param SCRIPT_FILENAME $document_root$fastcgi_script_name;
  }
}
